### ISSUE TITLE
UI Design Brainstorming

### ISSUE THREAD

**Issue by joshuanianji** [MLH-Fellowship/project-chad-wojak#5]
We are sticking with this: https://www.figma.com/file/bnm8PxVguZ3bYKEKhd4vz8/simply-portfolio-desing-(Community)?node-id=0%3A1

**Comment by joshuanianji** [comment]
https://kuon.space/#about

**Comment by CarrieKam** [comment]
https://www.figma.com/community/file/1103832220155964386?preview=fullscreen
![image](https://user-images.githubusercontent.com/36577595/171498449-0b0368b3-8320-4820-9d60-9cd91f3fb0c9.png)

**Comment by CarrieKam** [comment]
https://www.figma.com/community/file/1110561145934553397
![image](https://user-images.githubusercontent.com/36577595/171498366-a31c1740-c57c-406e-81ed-c37d3b6bd282.png)

**Comment by CarrieKam** [comment]
https://www.figma.com/community/file/1108576751773127426?preview=fullscreen
![image](https://user-images.githubusercontent.com/36577595/171499380-56d7ac53-c981-42b1-ab5f-78f6c9361513.png)
